import {
  LucideBell,
  LucideBookOpen,
  LucideBrain,
  LucideBriefcaseBusiness,
  LucideCalendarDays,
  LucideChartColumn,
  LucideChartLine,
  LucideCircleHelp,
  LucideFileText,
  LucideFlame,
  LucideFootprints,
  LucideGraduationCap,
  LucideLayoutDashboard,
  LucideListTodo,
  LucideMenu,
  LucideMessageSquare,
  LucideMic,
  LucideNotebookPen,
  LucidePin,
  LucidePinOff,
  LucidePlug,
  LucideRefreshCw,
  LucideRoute,
  LucideSearch,
  LucideSettings,
  LucideSmile,
  LucideSparkles,
  LucideStar,
  LucideTarget,
  LucideUsers,
  LucideWallet,
  LucideZap,
  provideLucideConfig,
  provideLucideIcons,
} from '@lucide/angular';

/** Icons used by sidebar / drawer / mobile nav / pin controls. */
export const NAV_LUCIDE_ICON_PROVIDERS = [
  provideLucideIcons(
    LucideLayoutDashboard,
    LucideListTodo,
    LucideCalendarDays,
    LucideRefreshCw,
    LucideFootprints,
    LucideFlame,
    LucideTarget,
    LucideMessageSquare,
    LucideWallet,
    LucideRoute,
    LucideChartColumn,
    LucideChartLine,
    LucideFileText,
    LucideBell,
    LucideSparkles,
    LucideSettings,
    LucideSmile,
    LucideBookOpen,
    LucideGraduationCap,
    LucideBriefcaseBusiness,
    LucideStar,
    LucideCircleHelp,
    LucideNotebookPen,
    LucideBrain,
    LucideMic,
    LucideUsers,
    LucidePlug,
    LucideZap,
    LucideSearch,
    LucidePin,
    LucidePinOff,
    LucideMenu,
  ),
  provideLucideConfig({
    size: 16,
    strokeWidth: 1.75,
  }),
];
